// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeHistory': string;
  'activeIntent': string;
  'activeUtterance': string;
  'chatPreview': string;
  'input': string;
  'intentBox': string;
  'mainView': string;
  'mainViewTable': string;
  'progressBox': string;
  'shortcut': string;
  'stickyActionBar': string;
  'stickyActionBarContent': string;
  'utterance': string;
}
declare var cssExports: CssExports;
export = cssExports;
