// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapsibleContainer': string;
  'header': string;
  'hidden': string;
  'sayNodeContextMenu': string;
  'subSection': string;
}
declare var cssExports: CssExports;
export = cssExports;
