// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeIntent': string;
  'activeUtterance': string;
  'applyAllButton': string;
  'contentFixed': string;
  'contentStretch': string;
  'headerTabs': string;
  'intentBox': string;
  'mainView': string;
  'mainViewTable': string;
  'padded': string;
  'sideList': string;
  'sideListItem': string;
  'sideListItemSelected': string;
  'sideListItemText': string;
  'sideListList': string;
  'sidePanel': string;
  'sidePanelContentStretch': string;
  'stickyActionBar': string;
  'stickyActionBarContent': string;
  'thAction': string;
  'thPhrase': string;
  'thUpdated': string;
  'utterance': string;
  'withStickyActionBar': string;
}
declare var cssExports: CssExports;
export = cssExports;
